permalink: /:title.html
url: http://blog.kissdata.com
author: vincentzhwg
paginate: 24
timezone: Asia/Shanghai


defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: page
            comments: true
