permalink: /:year/:month/:day/:title.html
author: vincentzhwg
paginate: 24
timezone: Asia/Shanghai
url: http://blog.kissdata.com

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "page"
            comments: "true"
