permalink: /:title.html
url: http://blog.kissdata.com
author: vincentzhwg
paginate: 24
timezone: Asia/Shanghai

collections:
    - posts:
        layout: "page"
        comments: "true"


#defaults:
#    -
#        scope:
#            path: ""
#            type: "posts"
#        values:
#            layout: "page"
#            comments: "true"
